config/routes.rb
Dareme::Application.routes.draw do

  resources :authentications

    mount Ckeditor::Engine => '/ckeditor'
    mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  
    resources :events
    match "/events/:id/vote_for" => 'events#vote_for', as: 'vote_for_event'
    match "/events/:id/vote_against" => 'events#vote_against', as: 'vote_against_event'
  

   

    resources :profiles, :only => [:update, :edit] 

    resources :videos, :only => [:edit, :new]
          
    resources :comments, :only => [:destroy, :create]

    resources :followings, only: [:destroy, :create]
  
    devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

    devise_scope :user do 
      match '/dashboard' => 'users#dashboard', as: 'dashboard'
      root :to => "users#dashboard"
      resources :users, only: [:show]
    end   

    match '/auth/:provider/callback' => 'authentications#create'
    
  match "/delayed_job" => DelayedJobWeb, :anchor => false

end

app/models/following.rb
class Following < ActiveRecord::Base

  #Associations
  	belongs_to :user, :inverse_of => :follows
	  belongs_to :followable, polymorphic: true
	  #belongs_to :following, class_name: 'Followable', polymorphic: true

  #Attributes
  	attr_accessible :followable_id, :followable_type, :user_id, :followable, :user_id,
      :created_at, :updated_at, :id

  #Callbacks
    validates_uniqueness_of :user_id, :scope => [:followable_id,:followable_type]

  #Validates
    validates :user_id, :presence => true
    validates :followable_type, :presence => true
    validates :followable_id, :presence => true


end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
include ApplicationHelper

  def index
    @followings = Following.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @followings }
    end
  end

  def create
    if session[:followable_type].to_s == 'User'
      @followable = User.find(session[:followable_id].to_i)
    elsif session[:followable_type].to_s == 'Event'
      @followable = Event.find(session[:followable_id].to_i)
    end

    @following = Following.new(followable: @followable, user_id:current_user.id )  

    #Rails.logger.info("PARAMS: #{params.inspect}")   
    respond_to do |format|
      if @following.save
        format.html { redirect_to @followable, notice: 'Are are now following...' }
      else
        format.html { render action: "new" }
      end
    end
  end


  def destroy
    @following = Following.find_by_id(params[:id])  
    if @following.followable_type == 'User' then
      @f = User.find(@following.followable_id.to_i)
    elsif @following.followable_type == 'Event' then
      @f = Event.find(@following.followable_id.to_i)
    end

   @following.destroy if Following.find_by_id_and_user_id(@following.id, @following.user_id)

    respond_to do |format|
      format.html { redirect_to :back, notice: "You are no longer following " + @f.slug }
      #format.html { redirect_to @f, notice: "You are no longer following..." }
      format.json { head :no_content }
    end
  end
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/views/followings/_form.html.erb
<%= form_for(@following) do |f| %>
  <% if @following.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@following.errors.count, "error") %> prohibited this following from being saved:</h2>

      <ul>
      <% @following.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :following_id %><br />
    <%= f.number_field :following_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/followings/edit.html.erb
<h1>Editing following</h1>

<%= render 'form' %>

<%= link_to 'Show', @following %> |
<%= link_to 'Back', followings_path %>

app/views/followings/index.html.erb
<h1>Listing followings</h1>

<table>
  <tr>
    <th>User</th>
    <th>Following</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @followings.each do |following| %>
  <tr>
    <td><%= following.user_id %></td>
    <td><%= following.following_id %></td>
    <td><%= link_to 'Show', following %></td>
    <td><%= link_to 'Edit', edit_following_path(following) %></td>
    <td><%= link_to 'Destroy', following, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Following', new_following_path %>

app/views/followings/new.html.erb
<h1>New following</h1>

<%= render 'form' %>

<%= link_to 'Back', followings_path %>

app/views/followings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @following.user_id %>
</p>

<p>
  <b>Following:</b>
  <%= @following.following_id %>
</p>


<%= link_to 'Edit', edit_following_path(@following) %> |
<%= link_to 'Back', followings_path %>