config/routes.rb
Dareme::Application.routes.draw do

  resources :authentications

    mount Ckeditor::Engine => '/ckeditor'
    mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  
    resources :events
    match "/events/:id/vote_for" => 'events#vote_for', as: 'vote_for_event'
    match "/events/:id/vote_against" => 'events#vote_against', as: 'vote_against_event'
  

   

    resources :profiles, :only => [:update, :edit] 

    resources :videos, :only => [:edit, :new]
          
    resources :comments, :only => [:destroy, :create]

    resources :followings, only: [:destroy, :create]
  
    devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

    devise_scope :user do 
      match '/dashboard' => 'users#dashboard', as: 'dashboard'
      root :to => "users#dashboard"
      resources :users, only: [:show]
    end   

    match '/auth/:provider/callback' => 'authentications#create'
    
  match "/delayed_job" => DelayedJobWeb, :anchor => false

end

app/models/event.rb
class Event < ActiveRecord::Base
  #Functionality
   #Friendly ID
    extend FriendlyId
    friendly_id :slug

   #Votable
    acts_as_voteable

   #PG Full Text Searching
    include PgSearch

   #multisearchable :against => [:title, :location, :description]
    pg_search_scope :event_search, 
      against: {:title => 'A',:location => 'B',:description => 'C'},
      using: {tsearch: {dictionary: "english", :prefix => true}}
      #http://railscasts.com/episodes/343-full-text-search-in-postgresql

	#Associations
	  belongs_to :user, :inverse_of => :events
    has_many :comments, :as => :commentable
    
    #@event.followers
    has_many :followings, :as => :followable
    has_many :followers, :through => :followings, :source => :user

    #@events.notifications
    has_many :notifications, as: :notifiable, dependent: :destroy

  #Attributes
    attr_accessible :description, :status, :raise_end, :event_time, :location, :minimum_raise, 
  	 :title, :user_id, :slug, :longitude,:latitude, :created_at, :updated_at,
     :request_video, :proof_video, :image, :remote_image_url, :image_cache, :remove_image

    mount_uploader :image, ImageUploader
  #Delayed Job Processing
    process_in_background :image


  #Callbacks
    before_save { |event| event.slug = event.slug.downcase }
    after_validation :geocoding
    after_update :create_notifications

  #Scopes
  	scope :default_order, order(:raise_end)
    scope :popular, joins("LEFT JOIN followings ON followings.followable_type = 'Event' AND followings.followable_id = events.id").select("events.*, count(*) as users_following").group("events.id").order("users_following desc")
    scope :status_open, where(status: 'Open')
    scope :status_completed, where(status: 'Completed')
    scope :limit_me, limit(100)


  #Validation
  	validates :slug, :presence => true
  	validates :slug, :format => { :with => /^\w+$/i,
    	:message => "only letters and numbers allowed" }
  	validates :slug, :exclusion => {:in => %w(contact dashboard profile 
  			profiles ass dick cunt prick shit fuck connection contacts connections 
  			home edit new create update post push), :message => "Please choose 
				a different user name"} 
  	validates :slug, :length => {:maximum => 50, 
  			:too_long => "%{count} characters is the maximum allowed"}
  	validates :slug, :length => {:minimum => 4, 
  			:too_short => "%{count} characters is the manimum allowed"}
  	validates :slug, :uniqueness => { :case_sensitive => false }
		validates :minimum_raise, :format => { :with => /^\d+??(?:\.\d{0,2})?$/ }, :numericality => {:greater_than => -1, :less_than => 250}

    validates :description, :presence => true
    validates :raise_end, :presence => true
    validates :event_time, :presence => true
    validates :location, :presence => true
    validates :title, :presence => true
    validates :slug, :presence => true
    validates :user_id, :presence => true

  #Other
    geocoded_by :location

  #Functions

    def geocoding
      if location_changed? and not location.nil? and not Rails.env.test? and not location.empty?
        geocode.delay
      else
        false
      end
    end


  def self.yt_session
#    puts self.to_yaml
#    auth = user.authentications.youtube
    #puts "------------_>AUTH"
    #puts auth.to_yaml

  end

    def total_vote
      self.votes_for + (self.votes_against*-1)
    end

    #Full Text Search
    def self.text_search(query)
      if query.present?
        event_search(query).limit_me
      else 
        scoped
      end
    end

    def create_notifications
      content = Array.new
      content << " has changed its location to " + self.location if location_changed?
      content << " has changed its description.. you may want to check it out" if description_changed?
      content << " is the new name of the event." if title_changed?
      content << " has changed its event time.  Don't be late." if event_time_changed?
      content << " has a new sweet image.  Check it out." if image_changed?

   
      if content.count > 1
        Notification.create(content:" was was just updated.  A lot.  Review it now!" , notifiable: self) 
      elsif content.count == 1
        Notification.create(content: content[0], notifiable: self) 
      end
      
      if status_changed?
        if self.status == 'Completed'
          content = " has just been completed.  Check it out now!  It's some crazy sh*t."         
          Notification.create(content: content, notifiable: self) 
        end
      end
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!


  def index
    @type = params[:index_type]
    @query = params[:query]

    @events = Event.includes(:user)

#    @a = Following.group(:followable_id, :followable_type).select("count(*) as count, followable_id, followable_type")

    if not @query.nil?
      @events = @events.text_search(@query).default_order.limit_me
    elsif @type == 'local'  #This needs some work.  Very non optimal especially if having a ton of events     
      @events = Event.near(current_user.profile, 500, {:order => :distance, :units => :mi}).limit_me
    elsif @type == 'completed'
      @events = @events.status_completed.default_order.limit_me
    elsif @type == 'most_popular_open'
      @events = @events.status_open.popular.limit_me    
    elsif @type == 'most_popular_completed'
      @events = @events.status_completed.popular.limit_me
    else
      @events = @events.status_open.default_order.limit_me
    end

    if @events.kind_of?(Array) then
      @events = Kaminari.paginate_array(@events).page(params[:page]).per(10)
    else
      @events = @events.page(params[:page]).per(10)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  def show
    @event = Event.find(params[:id])
    @following = Following.find_by_followable_type_and_followable_id_and_user_id("Event",@event.id,current_user.id)
    @comments = @event.comments.includes(:user).page(params[:page]).per(10)
    @comment = Comment.new
    @commentable = @event
      
    #Session variables for polymorphics
    session[:commentable_id] = @event.id
    session[:commentable_type] = @event.class  
    session[:followable_id] = @event.id
    session[:followable_type] = @event.class

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end
  def new
#    if not current_user.authentications.youtube.exists? then
#      redirect_to authentications_path, notice: 'Please authenticate with Youtube before creating an event!' 
#    else
      @event = Event.new
#    end    
  end

  def vote_for
    @event = Event.find(params[:id])
    if current_user.voted_on?(@event) then
      Vote.find_by_voteable_id_and_voteable_type(@event.id, 'Event').destroy
    else
      current_user.vote_exclusively_for(@event)
      respond_to do |format|
        format.js
      end
    end
  end

  def vote_against
    @event = Event.find(params[:id])
    if current_user.voted_on?(@event) then
      Vote.find_by_voteable_id_and_voteable_type(@event.id, 'Event').destroy
    else
      current_user.vote_exclusively_against(@event)
      respond_to do |format|
        format.js
      end
    end
  end


  def edit
    @event = Event.find(params[:id])
  #   auth = current_user.authentications.youtube.first

  # require 'faraday'

  # conn = Faraday.new(:url => 'https://accounts.google.com',:ssl => {:verify => false}) do |faraday|
  #  faraday.request  :url_encoded
  #  faraday.response :logger
  #  faraday.adapter  Faraday.default_adapter
  # end

  # results = conn.post '/o/oauth2/token', {'code' => auth.token,
  # 'client_id' => ENV['YOUTUBE_KEY'],
  # 'client_secret' => ENV['YOUTUBE_SECRET'],
  # 'redirect_uri' => "http://localhost:3000/auth/youtube/callback&",
  # 'grant_type' => 'authorization_code'}

  #   client = YouTubeIt::OAuth2Client.new(
  #    client_access_token: auth.token, 
  #    client_id: ENV['YOUTUBE_KEY'], 
  #    client_secret: ENV['YOUTUBE_SECRET'], 
  #    dev_key: ENV['YOUTUBE_DEV'])
   
#   puts "-------------------------results>"
 #  puts results.to_yaml
  # puts "---------------------__>end results"

#puts results.body.to_yaml
#    a = client.my_videos
    #puts a.to_yaml
  end

  def create
    @event = Event.new(params[:event])
    @event.user_id = current_user.id

    respond_to do |format|
      if @event.save
        Following.create(user_id: current_user.id, followable: @event)
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @event = Event.find(params[:id])
    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  def upload
    @upload_info = YouTubeIt::Client.new.upload_token(params, videos_url)
  end


end

app/helpers/events_helper.rb
module EventsHelper

	def youtube_embed(youtube_url)
		
	  if youtube_url[/youtu\.be\/([^\?]*)/]
	    youtube_id = $1
	  else
	    # Regex from # http://stackoverflow.com/questions/3452546/javascript-regex-how-to-get-youtube-video-id-from-url/4811367#4811367
	    youtube_url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
	    youtube_id = $5
	  end

		if youtube_url.nil? or youtube_url == "" or youtube_url.empty?
			''
		else
			%Q{<iframe title="YouTube video player" width="640" height="390" src="http://www.youtube.com/embed/#{ youtube_id }" frameborder="0" allowfullscreen></iframe>}
		end

	end

end

app/views/events/_display_event_in_search.html.erb
<%= link_to image_tag(event.image_url(:thumb_200)), event %> <br />
<%= link_to event.title, event %> 
<%= link_to 'Stop Following', Following.find_by_followable_type_and_followable_id_and_user_id("Event",event.id,current_user.id), method: :delete, data: { confirm: 'Are you sure?' } %> 

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<br />
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  </p>
  <div class="field">
    <%= f.label :event_time %><br />
    <%= f.datetime_select :event_time %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label 'Minimum $$ needed to do this' %><br />
    <%= f.text_field :minimum_raise %>
  </div>
  <div class="field">
    <%= f.label 'Bidding End' %><br />
    <%= f.datetime_select :raise_end %>
  </div>
  <div class="field">
    <%= f.label 'Custom SLUG / URL' %><br />
    <%= f.text_field :slug %>
  </div>
    <div class="field">
    <%= f.label :description %><br />
    <%= f.cktext_area :description, :input_html => { 
          :cols => 10, :rows => 30}  %>
  </div>

<h3>Request Video</h3>
  <div class="field">
    <%= f.label :request_video %><br />
    <%= f.text_field :request_video %>
  </div>
<br/>
<h3>Proof Video</h3>

  <div class="field">
    <%= f.label :proof_video %><br />
    <%= f.text_field :proof_video %>
  </div>
<br />
<br />




  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

app/views/events/index.html.erb
<%= link_to 'New Event', new_event_path %>
<br />
<br />

<%= link_to "All Open", events_path() %> | 
<%= link_to "Most Popular Completed", events_path(index_type: 'most_popular_completed') %> | 
<%= link_to "Most Popular Open", events_path(index_type: 'most_popular_open') %> |
<%= link_to "Local Events", events_path(index_type: 'local') %> | 
<%= link_to "All Completed", events_path(index_type: 'completed') %> 
<%= form_tag events_path, method: :get do %>
<p>
  <%= text_field_tag :query, params[:query] %>
  <%= submit_tag "Search", name: nil %>
</p>
<% end %>

<br />

<h1>Listing Events</h1>
<%= paginate @events %>
<br />
<table>
  <tr>
    <th></th>
    <th>User</th>
    <th>Title</th>
    <th>Event Date</th>
    <th>Location</th>
    <th>Bidding End</th>
    <th>Following</th>
    <th>Money Raised</th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= link_to image_tag(event.image_url(:thumb_50)), event  %></td>
    <td><%= link_to event.user.slug, event.user %><%# link_to event.user.profile.slug, '/profile/'+ event.user.profile.slug %></td>
    <td><%= link_to event.title, event %></td>

    <td><%= event.event_time %></td>
    <td><%= event.location %></td>
    <td><%= event.raise_end %></td>
    <td><%= event.followers.count %></td>
    <td>Coming Soon </td>
  </tr>
<% end %>
</table>

<br />

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Event </h1>
<% if current_user.id == @event.user_id then %>
  <%= link_to 'Edit', edit_event_path(@event) %> | <%= link_to 'Destroy', @event, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
<% if @following.nil? %>
  <%= link_to 'Follow Me!', followings_path, method: :post %> 
<% else %>
  <%= link_to 'Stop Following Me!', @following, method: :delete, data: { confirm: 'Are you sure?' } %> 
<% end %>
<br />
<% if @event.status == 'Complete' then %>
  <%= link_to image_tag('thumbs_up.png', width: "50", :border => 0), vote_for_event_path(@event), :remote => true  %>
  <%= link_to image_tag('thumbs_down.png', width: "50", :border => 0), vote_against_event_path(@event), :remote => true  %>
Total Votes: <%= @event.total_vote %>
<% end %>

<p>
<%= image_tag @event.image_url(:thumb_200) %>
</p>

<br />
<h1>Request Video</h1>
<%= raw youtube_embed(@event.request_video) %>
<br />
<h1>Proof Video</h1>
<%= raw youtube_embed(@event.proof_video) %>

<p>
  <b>User Name:</b>
  <%= link_to @event.user.slug, @event.user %>
</p>


<p>
  <b>Event Date:</b>
  <%= @event.event_time %>
</p>

<p>
  <b>Title:</b>
  <%= @event.title %>
</p>

<p>
  <b>Location:</b>
  <%= @event.location %>
</p>

<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=10&markers=#{@event.latitude}%2C#{@event.longitude}" %>
<p>
  <b>Minimum Cash to Raise:</b>
  <%= @event.minimum_raise %>
</p>

<p>
  <b>Bidding End:</b>
  <%= @event.raise_end %>
</p>

<p>
  <b>Description:</b>
  <%= @event.description.html_safe if not @event.description.nil? %>
</p>

<br />
<h1>Comments </h1>
<%= render "/comments/show_comments", :comments => @comments %>
<% if current_user.followed_events.exists?(@event) then %>
  <%= render '/comments/form' %>
<% else %>
  You must be following this event in order to post a comment.
<% end %>