config/routes.rb
Dareme::Application.routes.draw do

  resources :authentications

    mount Ckeditor::Engine => '/ckeditor'
    mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  
    resources :events
    match "/events/:id/vote_for" => 'events#vote_for', as: 'vote_for_event'
    match "/events/:id/vote_against" => 'events#vote_against', as: 'vote_against_event'
  

   

    resources :profiles, :only => [:update, :edit] 

    resources :videos, :only => [:edit, :new]
          
    resources :comments, :only => [:destroy, :create]

    resources :followings, only: [:destroy, :create]
  
    devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

    devise_scope :user do 
      match '/dashboard' => 'users#dashboard', as: 'dashboard'
      root :to => "users#dashboard"
      resources :users, only: [:show]
    end   

    match '/auth/:provider/callback' => 'authentications#create'
    
  match "/delayed_job" => DelayedJobWeb, :anchor => false

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dare Me</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<br />
<ul class="hmenu">
	<% if user_signed_in? %>
  <li> <%= link_to 'Dashboard', dashboard_path%> </li>  
  <li> <%= link_to 'Show Dares', events_path%> </li>  
  <li> <%= link_to 'Profile', current_user %></li> 
  <li> <%= link_to 'Authentications', authentications_url %></li> 
  <%= render 'devise/menu/registration_items' %>
  <%= render 'devise/menu/login_items' %>
  <li> <%= link_to 'Sign In With Facebook', user_omniauth_authorize_path(:facebook) %></li>
  <li> <%= link_to 'Sign In With YouTube', user_omniauth_authorize_path(:youtube) %></li>
  <% end %>
</ul>
<br />
<%= yield %>

</body>
</html>